C_OBJS=mb_tests.o xv6.o kalloc.o xv6_string.o disk.o bio.o ide.o fs.o file.o
ASM_OBJS=cos_asm_scheduler.o inv.o
COMPONENT=vm_xv6_boot.o
INTERFACES=
DEPENDENCIES=lock
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format -lcos_kernel_api

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
